### ISSUE TITLE
Методичная разметка личного проекта

### ISSUE THREAD

**Issue by MammaSonnim** [htmlacademy-adaptive/124052-pink#2]
**Задание состоит из нескольких шагов:**

1. В форке выбранного личного проекта создайте ветку module2-task1 и в ней выполните разметку трёх страниц мобильной версии проекта.
> 1.1 Разметка должна быть выполнена в соответствии с одной из методологий: БЭМ или SMACSS.
> 1.2 Не используйте обозначение мобильной версии -mobile в именах файлов или классов. 
> 1.3 На этом этапе нужна только HTML-разметка, без CSS. Изображения вырезать не нужно — используйте вместо них заглушки.

2. Создайте пулреквест из ветки module2-task1 вашего форка в мастер-репозиторий и нажмите зелёную кнопку «Всё выполнила, можно проверять» в интерфейсе интенсива.

**Comment by aalexeev239** [comment]
@MammaSonnim используй изображения медведиков :)
